name: Build
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ["t2linux-repo", "t2linux-config", "t2linux-audio", "kernel"]
    steps:
      - name: "Increase Disk Space"
        if: contains(matrix.package, 'kernel')
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo rm -rf /home/linuxbrew
          sudo apt-get remove -y --purge fonts-noto-color-emoji subversion ssh \
              sshpass g++ gcc gnupg2 imagemagick jq libmagic-dev \
              libmagickcore-dev	libmagickwand-dev	libssl-dev \
              mercurial openssh-client p7zip-full	ftp bison
          sudo apt-get autoremove -y

      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Build"
        run: |
          mkdir -p _output
          docker run -t --privileged \
          -v "$PWD":/repo \
          -e PACKAGE \
          ghcr.io/t2linux/fedora-kernel-build:latest \
          /repo/build-packages.sh
        env:
          PACKAGE: ${{ matrix.package }}

      - name: "Check Build Artifacts"
        run: |
          stat --printf='' _output/$PACKAGE*.rpm

      - name: "Upload Build Artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.package }}
          path: _output/*.rpm

  upload-artifact:
    needs: ["build"]
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Download Build Artifacts"
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: "Create Unified Artifact"
        run: |
          mkdir _output
          cp artifacts/*/*.rpm _output

      - name: "Sign Packages"
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker run -t \
            -v $PWD:/repo \
            -e RPM_SIGNING_PRIVATE_KEY_B64 \
            ghcr.io/t2linux/fedora-kernel-build:latest \
            /repo/sign-packages.sh
        env:
          RPM_SIGNING_PRIVATE_KEY_B64: ${{ secrets.RPM_SIGNING_PRIVATE_KEY_B64 }}

      - name: "Upload Unified Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: _output/*.rpm
