name: Build
on:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Lint"
        run: |
          docker run \
            --quiet \
            -v "$PWD":/repo \
            ghcr.io/t2linux/fedora-dev:latest \
            /repo/lint.sh

  build:
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          since_last_remote_commit: true 
          files: |
            kernel/*
            copr-sharpenedblade-t2linux-release/*
            rust-tiny-dfr/*
            t2linux-audio/*
            t2linux-config/*
          dir_names: "true"

      - name: "Increase Disk Space"
        if: ${{ contains(steps.changed-files.outputs.modified_files, 'kernel') || (steps.changed-files.outputs.any_changed == 'false') }}
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo rm -rf /home/linuxbrew
          sudo apt-get remove -y --purge fonts-noto-color-emoji subversion \
              sshpass g++ gcc gnupg2 imagemagick jq libmagic-dev \
              libmagickcore-dev	libmagickwand-dev	libssl-dev \
              mercurial openssh-client p7zip-full	ftp bison
          sudo apt-get autoremove -y

      - name: "Build"
        run: |
          docker run \
            --privileged \
            -v "$PWD":/repo \
            ghcr.io/t2linux/fedora-dev:latest \
            /repo/build-packages.sh ${{ steps.changed-files.outputs.all_changed_files }}

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: builddir/packages/*.rpm
