name: Build
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ["t2linux-repo", "t2linux-config", "t2linux-audio"]
    steps:
      - name: "Increase Disk Space"
        if: contains(matrix.package, 'kernel')
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc

      - name: "Checkout"
        uses: actions/checkout@v3
      
      - name: "Build"
        run: |
          mkdir -p _output
          docker run -t --privileged \
          -v "$PWD":/repo \
          -e RPM_SIGNING_PRIVATE_KEY_B64 \
          -e PACKAGE \
          fedora:38 /bin/bash -c "/repo/build-packages.sh"
        env: 
          RPM_SIGNING_PRIVATE_KEY_B64: ${{ secrets.RPM_SIGNING_PRIVATE_KEY_B64 }}
          PACKAGE: ${{ matrix.package }}

      - name: "Check Build Artifacts"
        run: |
          stat --printf='' _output/$PACKAGE*.rpm

      - name: "Upload Build Artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.package }}
          path: _output/*.rpm

  upload-artifact:
    needs: ["build"]
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3      

      - name: "Download Build Artifacts"
        uses: actions/download-artifact@v3
        with:
          path: artifacts
  
      - name: "Create Unified Artifact"
        run: |
          mkdir _output
          cp artifacts/*/*.rpm _output

      - name: "Sign Packages"
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker run -t \
            -v $PWD:/repo \
            fedora:38 /bin/bash -c "/repo/sign-packages.sh"

      - name: "Upload Unified Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: _output/*.rpm