name: COPR Webhook
on:
  push:
    branches:
      - "main"
    paths:
      - "kernel/*"
      - "t2linux-config/*"
      - "t2linux-audio/*"
      - "rust-tiny-dfr/*"
      - "copr-sharpenedblade-t2linux-release/*"

jobs:
  copr-webhook:
    runs-on: ubuntu-latest
    steps:

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          since_last_remote_commit: true
          dir_names: "true"
      
      - name: "Trigger COPR webhook"
        run: |
          for package in "$CHANGED_PACKAGES"; do
            curl -X POST $COPR_WEBHOOK/$package
          done
        env:
          COPR_WEBHOOK: ${{ secrets.COPR_WEBHOOK }}
          CHANGED_PACKAGES: ${{ steps.changed-files.outputs.all_changed_files }}
